-- Migration: Normalize customers.region and customers.salesperson
-- Target: PostgreSQL / Supabase
-- Date: 2026-03-25

begin;

-- 1) New master tables
create table if not exists public.regions (
  id bigint generated by default as identity primary key,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.salespeople (
  id bigint generated by default as identity primary key,
  name text not null,
  region_id bigint null references public.regions(id) on update cascade on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Case-insensitive uniqueness through expression indexes
create unique index if not exists regions_name_unique_idx
  on public.regions (lower(btrim(name)));

create unique index if not exists salespeople_name_unique_idx
  on public.salespeople (lower(btrim(name)));

-- 2) Add FK columns to customers (keep legacy text columns for phased rollout)
alter table public.customers
  add column if not exists region_id bigint null,
  add column if not exists salesperson_id bigint null;

-- 3) Add foreign keys (if missing)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customers_region_id_fkey'
  ) then
    alter table public.customers
      add constraint customers_region_id_fkey
      foreign key (region_id)
      references public.regions(id)
      on update cascade
      on delete set null;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'customers_salesperson_id_fkey'
  ) then
    alter table public.customers
      add constraint customers_salesperson_id_fkey
      foreign key (salesperson_id)
      references public.salespeople(id)
      on update cascade
      on delete set null;
  end if;
end
$$;

create index if not exists customers_region_id_idx on public.customers(region_id);
create index if not exists customers_salesperson_id_idx on public.customers(salesperson_id);

-- 4) Seed regions from existing customers.region text
insert into public.regions (name)
select distinct btrim(c.region) as name
from public.customers c
where c.region is not null
  and btrim(c.region) <> ''
  and not exists (
    select 1
    from public.regions r
    where lower(btrim(r.name)) = lower(btrim(c.region))
  );

-- 5) Seed salespeople from existing customers.salesperson text
insert into public.salespeople (name)
select distinct btrim(c.salesperson) as name
from public.customers c
where c.salesperson is not null
  and btrim(c.salesperson) <> ''
  and not exists (
    select 1
    from public.salespeople s
    where lower(btrim(s.name)) = lower(btrim(c.salesperson))
  );

-- 6) Backfill customers.region_id from legacy text
update public.customers c
set region_id = r.id
from public.regions r
where c.region is not null
  and btrim(c.region) <> ''
  and c.region_id is null
  and lower(btrim(c.region)) = lower(btrim(r.name));

-- 7) Backfill customers.salesperson_id from legacy text
update public.customers c
set salesperson_id = s.id
from public.salespeople s
where c.salesperson is not null
  and btrim(c.salesperson) <> ''
  and c.salesperson_id is null
  and lower(btrim(c.salesperson)) = lower(btrim(s.name));

-- 8) Optional enrichment: if a salesperson maps to exactly one region, store it
update public.salespeople s
set region_id = x.region_id
from (
  select
    c.salesperson_id,
    min(c.region_id) as region_id
  from public.customers c
  where c.salesperson_id is not null
    and c.region_id is not null
  group by c.salesperson_id
  having count(distinct c.region_id) = 1
) x
where s.id = x.salesperson_id
  and s.region_id is null;

commit;
