begin;

create table if not exists public.original_pattern (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.original_brands(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint original_pattern_brand_name_key unique (brand_id, name)
);

create index if not exists original_pattern_brand_id_idx
  on public.original_pattern (brand_id);

create index if not exists original_pattern_sort_order_idx
  on public.original_pattern (sort_order, name);

alter table if exists public.original_pattern enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'original_pattern'
      and policyname = 'original_pattern_select_policy'
  ) then
    create policy original_pattern_select_policy
      on public.original_pattern
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'original_pattern'
      and policyname = 'original_pattern_insert_policy'
  ) then
    create policy original_pattern_insert_policy
      on public.original_pattern
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'original_pattern'
      and policyname = 'original_pattern_update_policy'
  ) then
    create policy original_pattern_update_policy
      on public.original_pattern
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'original_pattern'
      and policyname = 'original_pattern_delete_policy'
  ) then
    create policy original_pattern_delete_policy
      on public.original_pattern
      for delete
      to anon, authenticated
      using (true);
  end if;
end
$$;

commit;